// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Environment variables required - no hardcoded fallbacks for security
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('CRITICAL: Supabase credentials not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env file');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: false,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    // Faster auth by using PKCE
    flowType: 'pkce',
  },
  // Performance optimizations
  global: {
    headers: {
      // Enable compression for faster responses
      'Accept-Encoding': 'gzip, deflate, br',
    },
  },
  // Realtime configuration
  realtime: {
    // Reduce heartbeat for better battery/performance
    params: {
      eventsPerSecond: 10,
    },
  },
  // Database connection pooling
  db: {
    schema: 'public',
  },
});

export const getFunctionUrl = (name: string) => `${SUPABASE_URL}/functions/v1/${name}`;

// Helper to abort slow requests
export const createAbortableQuery = (timeoutMs = 10000) => {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  return {
    signal: controller.signal,
    cleanup: () => clearTimeout(timeoutId),
  };
};

// GDPR-compliant session timeout (15 minutes)
const SESSION_TIMEOUT_MS = 15 * 60 * 1000;
let sessionTimer: ReturnType<typeof setTimeout> | undefined;

const handleSessionTimeout = async () => {
  await supabase.auth.signOut();
  window.location.href = '/login?reason=timeout';
};

const resetSessionTimeout = () => {
  if (sessionTimer) clearTimeout(sessionTimer);
  sessionTimer = setTimeout(handleSessionTimeout, SESSION_TIMEOUT_MS);
};

// Track user activity to reset timeout
if (typeof window !== 'undefined') {
  ['mousedown', 'keydown', 'scroll', 'touchstart'].forEach(event => {
    document.addEventListener(event, resetSessionTimeout, { passive: true });
  });

  // Start initial timer
  resetSessionTimeout();
}